# Generated by Django 3.2.5 on 2021-07-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20210708_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='products',
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(related_name='products', to='collection.Collection'),
        ),
    ]
