# Generated by Django 3.2.5 on 2021-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20210709_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(related_name='products', to='collection.Collection'),
        ),
    ]
