# Generated by Django 3.2.5 on 2021-07-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20210709_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
