# Generated by Django 3.2.5 on 2021-07-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
    ]
