# Generated by Django 3.2.5 on 2021-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_alter_collection_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='collection', to='collection.Product'),
        ),
    ]
